apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "todo-kafka.fullname" . }}-kafka
spec:
  serviceName: {{ include "todo-kafka.fullname" . }}-kafka
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.kafka.image }}
        ports:
        - containerPort: {{ .Values.kafka.broker.port }}
        - containerPort: {{ .Values.kafka.broker.jmxPort }}
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ include \"todo-kafka.fullname\" . }}-zookeeper:{{ .Values.zookeeper.port }}"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://{{ include \"todo-kafka.fullname\" . }}-kafka:{{ .Values.kafka.broker.port }}"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        resources:
          {{- toYaml .Values.kafka.resources | nindent 10 }}
